### ISSUE TITLE
Frecuencia de actualización de datos

### ISSUE THREAD

**Issue by croblero** [felipetodev/covid-vacuna-chile#1]
Hola @felipetodev!

Primero que todo, gracias por esta ordenada fuente de datos, ya que me permitió hacer un bot de Twitter que publica los datos. El bot es [@AvanceVacunas](https://twitter.com/AvanceVacunas) y ya cuenta con tweets desde el inicio del proceso de vacunación al 13/05/2021, informando del avance en porcentaje de personas con dos dosis a nivel nacional y con números absolutos de las personas con una y dos dosis a nivel nacional. Le agregué una barra de progreso simple también.

Ahora, mi duda es sobre las fuentes de los datos y la frecuencia de actualización, ya que en el archivo de hoy sigue siendo el 13/05/2021 la última fecha con información. Como mi idea es poder definir una hora para la actualización diaria, quería saber si tienes definido un horario de publicación de los datos y si estos desfases de fechas son frecuentes, para poder adaptar mi bot.

Desde ya, muchas gracias por tu tiempo. Saludos,

Cristián.

**Comment by felipetodev** [comment]
Hola Cristian,

Me alegra que te esté siendo de ayuda!, acabo de revisar la base de datos
del MinCiencia, y al parecer agregaron un nuevo fabricante de vacuna (
Astra-Zeneca) y esta debe ser el motivo del desfase. Dejame que lo arreglo
hoy mismo para que todo cuadre a la perfección.

En mi caso, la página tiene un script y se actualiza cada 6 hrs según los
datos que encuentra en el repositorio del MinCiencia, pasa que a veces
actualizan antes los de Vacunaciones distribuidas, y luego a las horas o al
día siguiente actualizan las vacunaciones según fabricantes, revisare que
onda, ya que no he estado al tanto de la app!

Estamos en contacto y gracias por contactar 😉
Atte,

*Felipe OSSANDON*

**Comment by felipetodev** [comment]
https://covid-vacuna-chile.vercel.app/data/latest.json
https://covid-vacuna-chile.vercel.app/data/trademark_latest.json

Podríamos estipular un horario en particular para actualizar la data
